### ISSUE TITLE
test video

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [Ghostbird/Analogue-Gauge-Reader#1]
Hi, Can you provide the test video to test the program? Can it work on single image input as well?

**Comment by Ghostbird** [comment]
I have uploaded the [test video](../releases/tag/test-video)
The algorithm works on every frame separately IIRC. So you can take the algorithm out of the video loop and feed a single frame to it.

**Comment by MuhammadAsadJaved** [comment]
@Ghostbird 
                     Thank you for the video and it can use without any error. 
My task is a little bit different.  I just want to pass a single image and then output the reading. I have two kinds of meters. one is same as your and one is round one. 
Please see the attached images. 

How I can perform that task? I do not need to draw any curve,  Just read output according to the position of the needle in the still meter and print the output. 

![4489](https://user-images.githubusercontent.com/28862708/100561988-4b802e00-32f5-11eb-8e56-7edcdc45fa31.jpg)
![3350](https://user-images.githubusercontent.com/28862708/100562010-5935b380-32f5-11eb-9b90-302cb29b4dfe.jpg)

**Comment by Ghostbird** [comment]
My algorithm isn't usable for you. I use a hue filter to get the mask, and that won't do here, since your needles do not have a very specific hue. You'll have to learn how to write your own algorithm, but you can use my code as an example. You'll probably still use the Hough Lines function that I use at the end of my algorithm
